### ISSUE TITLE
library not accessible from bintray

### ISSUE THREAD

**Issue by tikeman** [Crysis21/KeyboardHeightProvider#10]
Recently having issues fetching library from bintray.

**Comment by atearaeshaal** [comment]
same in mine...have u solved it?

**Comment by sagarnayak** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsDebug'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not download keyboardheightprovider-0.0.9.aar (com.hold1:keyboardheightprovider:0.0.9)
      > Could not get resource 'https://dl.bintray.com/crysis21/Android/com/hold1/keyboardheightprovider/0.0.9/keyboardheightprovider-0.0.9.aar'.
         > Could not GET 'https://dl.bintray.com/crysis21/Android/com/hold1/keyboardheightprovider/0.0.9/keyboardheightprovider-0.0.9.aar'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
1 actionable task: 1 executed

**Comment by scholzi100** [comment]
BinTray was shutdown: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Some forks did publish it to other repositories:
- https://github.com/ConsultantPlus-Mobile/KeyboardHeightProvider/tree/release-1.0.0
- https://github.com/conservify/KeyboardHeightProvider/tree/feature/local-publish

**Comment by Crysis21** [comment]
Project has been migrated to maven central. it has a new package name, please see the Readme file.
