### ISSUE TITLE
Could not GET 'https://dl.bintray.com/crysis21/Android/com/hold1/keyboardheightprovider/0.0.9/keyboardheightprovider-0.0.9.aar'. Received status code 403 from server: Forbidden 

### ISSUE THREAD

**Issue by muhammedahsanau** [Crysis21/KeyboardHeightProvider#11]
**_, kindly help what is wrong with the server , its not giving responses ._**

**Comment by androidcompanion** [comment]
Same Error Here

**Comment by fukemy** [comment]
just copy file resource instead of gradle. this library will not update more, i think so
Or better find other library

**Comment by scholzi100** [comment]
BinTray was shutdown: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Some forks did publish it to other repositories:
- https://github.com/ConsultantPlus-Mobile/KeyboardHeightProvider/tree/release-1.0.0
- https://github.com/conservify/KeyboardHeightProvider/tree/feature/local-publish

**Comment by Crysis21** [comment]
Project has been migrated to maven central. it has a new package name, please see the Readme file.
