### ISSUE TITLE
Screen is Flickering on Opening Keyboard

### ISSUE THREAD

**Issue by pingatkaran** [Crysis21/KeyboardHeightProvider#12]
[Help Needed]The Screen Flickers on Opening the keyboard and layout moves up and comes down.

**Comment by JurajBegovac** [comment]
This is happening to me as well - I debugged it and it seems that sometimes it calculates double height and then the correct height. But the double height change is visible if some other view depends on `keyboardHeight`.

I don't have some working solution yet :)

**Comment by pingatkaran** [comment]
@JurajBegovac Well, adjustNothing worked.

**Comment by JurajBegovac** [comment]
@pingatkaran I still have the same issue 🤷

**Comment by pingatkaran** [comment]
@JurajBegovac  paste your gist link.

**Comment by Crysis21** [comment]
use this https://github.com/android/user-interface-samples/tree/master/WindowInsetsAnimation
