### ISSUE TITLE
Please make change in your code part in Setup on github

### ISSUE THREAD

**Issue by mrvinay07** [Crysis21/KeyboardHeightProvider#21]
This is the correct Dependency
`implementation 'ro.holdone:keyboardheightprovider:1.0.3'` 
Please replace dot(.) with a colon(:)  ... in the given screenshot you can easily find out where to change what to change.

<img width="842" alt="Screenshot 2021-09-13 at 2 43 44 PM" src="https://user-images.githubusercontent.com/54042642/133057733-e0aedc0a-7b03-42d2-9a38-473e27d3a028.png">

**Comment by Crysis21** [comment]
nice catch. totally missed it. thanks :)
