### ISSUE TITLE
KeyboardHeight is negative instead of zero

### ISSUE THREAD

**Issue by mlilienberg** [Crysis21/KeyboardHeightProvider#3]
Reported on Samsung phones (Samsung Galaxy S8). When using system setting: "Settings -> Display > Navigation Bar > Show and hide button" to hide the Navigation Bar, then the KeyBoardHeightProvider reports negative value for KeyBoardHeight. I helped myself by changing the calculation to:

val keyboardHeight = Math.max(screenSize.y + notchHeight - rect.bottom, 0)

**Comment by Crysis21** [comment]
Nice catch. I have a samsung phone but I haven't experimented with the hiding of nav bar.

**Comment by shripal-is-in** [comment]
This is also reproduced on Xiaomi phones with MIUI11+

**Comment by Crysis21** [comment]
use this https://github.com/android/user-interface-samples/tree/master/WindowInsetsAnimation
