### ISSUE TITLE
Query not issue

### ISSUE THREAD

**Issue by asthagarg2428** [Crysis21/KeyboardHeightProvider#4]
Does the height of keyboard includes the toolbar height? status bar of device?
I'm getting 747 as height, what all it includes? I want to show a button just above the keyboard.

**Comment by Crysis21** [comment]
that is the height of the keyboard only. basically, is computed by having an invisible floating window as tall as your screen. when the keyboard shows, that window is resized and the difference if the keyboard size in pixels.

**Comment by Crysis21** [comment]
I handle it like this in my apps

```kotlin

    private fun handleKeyboardPopup(size: Int) {
        resultsBtn.translationY = -size.toFloat() + if (size > 0) resources.getDimensionPixelSize(R.dimen.bottom_navigation_height) else 0
    }
```
