### ISSUE TITLE
Height of full screen

### ISSUE THREAD

**Issue by alexandre-thauvin** [Crysis21/KeyboardHeightProvider#5]
The height that I receive when the keyboard is displayed is the height of my whole screen.
On OnePlus6, Android 9 Pie

**Comment by Crysis21** [comment]
Unfortunately I don't have any one plus devices. If you could debug a bit the issue and post some debugger values, maybe we can figure it out.

**Comment by Crysis21** [comment]
use this https://github.com/android/user-interface-samples/tree/master/WindowInsetsAnimation
