### ISSUE TITLE
Keyboard height issue on target api 29

### ISSUE THREAD

**Issue by Tushar-Salvi** [Crysis21/KeyboardHeightProvider#6]
Keyboard height providing is deprecated on target api 29, is there any solution? Please help

**Comment by Crysis21** [comment]
I haven't tested it yet. Do you know which APIs are deprecated? I will try to take a look in the weekend.

**Comment by Tushar-Salvi** [comment]
Hi Crysis,

It's working fine.

**Comment by Crysis21** [comment]
ok than. closing this issue.
